const CommonActionTypes = {
  START_AUTHENTICATION: "START_AUTHENTICATION",
  SUCCESS_AUTHENTICATION: "SUCCESS_AUTHENTICATION",
  FAILURE_AUTHENTICATION: "FAILURE_AUTHENTICATION",
  FINISH_AUTHENTICATION: "FINISH_AUTHENTICATION",

  START_GET_CLIENTS: "START_GET_CLIENTS",
  SUCCESS_GET_CLIENTS: "SUCCESS_GET_CLIENTS",
  FAILURE_GET_CLIENTS: "FAILURE_GET_CLIENTS",
  FINISH_GET_CLIENTS: "FINISH_GET_CLIENTS",

  START_LOGOUT: "START_LOGOUT",
  SUCCESS_LOGOUT: "SUCCESS_LOGOUT",
  FAILURE_LOGOUT: "FAILURE_LOGOUT",
  FINISH_LOGOUT: "FINISH_LOGOUT",
};

export default CommonActionTypes;
